#!/bin/bash

MOVIES=("Pushpa" "rrr" "GC")

#index starts from 0 to and size is 3

echo "First movie is ${MOVIES[0]}"
echo "Second movie is ${MOVIES[1]}"
echo "Third movie is ${MOVIES[2]}"
echo "Movie list is ${MOVIES[1 2]}"
echo "All movies are ${MOVIES[@]}"

