#!/bin/bash

NUMBER=$1

# -gt(greater than) , -lt(lesser than) , -eq(equals to) , -ge(greater than equals to) , -le(less than equals to)

if [ $NUMBER -gt 100 ]
then 
    echo "Given number : $NUMBER is greater than 100"
else
    echo "Given number : $NUMBER is less than 100"
fi