#!/bin/bash

USERID=$(id -u)

if [ $USERID -ne 0 ]
then 
    echo " You must be a root user"
    exit 1
fi

dnf list installed mysql

if [ $? -ne 0 ] 
then 
    dnf install mysql
    if [ $? -ne 0 ]
    then 
        echo " My sql installation failure"
        exit 1
    else
        echo " My sql installation success"
    fi
else
    echo "My sql installation is already installed"
fi

if [ $? -ne 0 ]
then 
    dnf install git
    if [ $? -ne 0 ]
    then
        echo "My sql install failure"
        exit 1
    else 
        echo "my sql success"
    fi
else 
    echo "my git is already installed"
fi

