#!/bin/bash

USERID=$(id -u)

VALIDATE() {
    if [ $1 -ne 0 ]
    then 
        echo "$2 installation is failure"
        exit 1
    else  
        echo "$2 installation is success"
    fi
}

if [ $USERID -ne 0 ]
then
    echo"You must be a root user to execute this script"
    exit 1
fi

dnf list installed mysql
if [ $? -ne 0 ]
then
    dnf install mysql
    VALIDATE $? "Installation MySQL"
else
    echo"My SQL is already installed"
fi

dnf list installed git
if [ $? -ne 0 ]
then 
    dnf install git
    VALIDATE $? "Installation git"
else
    "Git is already installed"
fi