#! /bin/bash

USERID=$(id -u)
VALIDATE() {
if [ $1 -ne 0 ]
    then
        echo "$2 installation failed"
        exit 1
    else
        echo "$2 installation success"
    fi
}
if [ $USERID -ne 0 ]
then 
    echo "Entered user is not root user , run script with root user"
    exit 1
fi

dnf list installed mysql
if [ $? -ne 0 ]
then 
    dnf install mysql -y
    VALIDATE $? "MySQL"
else
    echo "MySQL is already installed"
fi
    
dnf list installed git
if [ $? -ne 0 ]
then
    dnf install git
    VALIDATE $? "Git"
else
    echo "Git is already installed"
fi